### ISSUE TITLE
Sugestão: JS runtime (Bun)

### ISSUE THREAD

**Issue by kassane** [jeffotoni/benchmark#1]
https://bun.sh/

**Comment by jeffotoni** [comment]
Vou testar para vermos, o layout e visual é lindão ....

**Comment by kassane** [comment]
Blz! Mas vale ressaltar (como já descrito no site do projeto), independente de qualquer resultado, o Bun, diferente dos concorrentes diretos (deno & node), utiliza o JSCore (webkit) ao invés do V8.

**Comment by jeffotoni** [comment]
Preciso fazer alguns testes para ver se consigo criar um server e depois fazer chamadas em server.

**Comment by jeffotoni** [comment]
![image](https://user-images.githubusercontent.com/1092879/235335989-51a7e4a0-cbde-498c-949e-9f2774d0b469.png)

**Comment by jeffotoni** [comment]
Fora que a memória está nas ALTURAS

**Comment by jeffotoni** [comment]
![image](https://user-images.githubusercontent.com/1092879/235336081-d6a8a14f-f055-4ec4-bf24-ae3c45e1aa78.png)

**Comment by jeffotoni** [comment]
![image](https://user-images.githubusercontent.com/1092879/235336105-9fe34b24-2c9f-4121-8061-1de0f84a53d5.png)

**Comment by kassane** [comment]
> Fora que a memória está nas ALTURAS

Isto seria um caso de: "desempenho a qualquer custo!". :smile: :rocket: 

Brincadeira a parte... o Bun utiliza o máximo de recursos por default. (embora o autor emprega ser causa do JsC)
Inclusive nesta página referencia, especificamente sobre o consumo de memória para benchmarks:
https://bun.sh/docs/project/benchmarking#measuring-memory-usage

**Comment by jeffotoni** [comment]
![image](https://user-images.githubusercontent.com/1092879/235672060-a1c55729-2ad5-44e6-8407-0a7f5f87ca52.png)

**Comment by jeffotoni** [comment]
A memória realmente diminui mas os requests caiu d+++++++ então muito fraca para este cenário heeeee.
